[package]
name = "minwgsl"
version = "1.0.3"
authors = ["robertpakalns"]
edition = "2024"
description = "WGSL minifier written in Rust"
repository = "https://github.com/robertpakalns/minwgsl"
license-file = "./LICENSE"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = "symbols"
debug = false
debug-assertions = false

[lib]
crate-type = ["cdylib"]

[dependencies]
hashbrown = { version = "0.17.1", default-features = false }
naga = { version = "30.0.0", default-features = false, features = [
  "wgsl-in",
  "wgsl-out",
] }
wasm-bindgen = { version = "0.2.126", default-features = false }
wee_alloc = { version = "0.4.5", default-features = false }
