[package]
name = "minwgsl"
version = "1.0.1"
authors = ["robertpakalns"]
edition = "2024"
description = "WGSL minifier written in Rust"
repository = "https://github.com/robertpakalns/minwgsl"
license-file = "./LICENSE"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = "symbols"
debug = false
debug-assertions = false

[lib]
crate-type = ["cdylib"]

[dependencies]
hashbrown = { version = "0.16.1", default-features = false }
# Allows building WASM with no_std
naga = { version = "28.0.0", git = "https://github.com/robertpakalns/wgpu.git", rev = "da1e5cdf330ef64f3b8eb016f477a8365317cf5b", default-features = false, features = [
  "wgsl-in",
  "wgsl-out",
] }
wasm-bindgen = { version = "0.2.108", default-features = false }
wee_alloc = { version = "0.4.5", default-features = false }
